# Generated by Django 3.2.6 on 2024-10-12 10:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(editable=False, max_length=255, verbose_name='User ID')),
                ('user_email', models.CharField(max_length=255, verbose_name='User email')),
                ('title', models.CharField(blank=True, default='Untitled project', max_length=110, verbose_name='Title')),
                ('deliverables', models.CharField(blank=True, default='', max_length=500, verbose_name='Deliverables')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='Description')),
                ('goal', models.CharField(blank=True, default='', max_length=500, verbose_name='Goal')),
                ('duration', models.PositiveIntegerField(blank=True, default=1, verbose_name='Amount of work')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Date updated')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100, verbose_name='Title')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Date updated')),
                ('type', models.CharField(choices=[('chat', 'Chat'), ('playground', 'Playground')], default='chat', max_length=10, verbose_name='Type')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='jlab.project', verbose_name='Project')),
            ],
            options={
                'ordering': ['-date_updated'],
            },
        ),
        migrations.CreateModel(
            name='TaskMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_answer', models.BooleanField(blank=True, default=False, verbose_name='Is an answer by AI?')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('csat', models.BooleanField(blank=True, default=None, null=True, verbose_name='CSAT Liked?')),
                ('parameters', models.JSONField(blank=True, null=True, verbose_name='Prompt parameters')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.agent', verbose_name='Agent')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='jlab.projecttask', verbose_name='Task')),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='MessageObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('quote', 'Quote')], max_length=10, verbose_name='Type')),
                ('content', models.TextField(blank=True, default='', verbose_name='Content')),
                ('file', models.FileField(blank=True, null=True, upload_to='jlab/ai_chat/', verbose_name='File')),
                ('status', models.CharField(choices=[('initial', 'Initial'), ('accepted', 'Accepted'), ('error', 'Error'), ('retry', 'Retry'), ('audio_ready', 'Audio Ready'), ('video_ready', 'Video Ready'), ('image_ready', 'Image Ready'), ('awaiting', 'Awaiting')], default='initial', max_length=20, verbose_name='Status')),
                ('video_id', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Synclab video ID')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objs', to='jlab.taskmessage', verbose_name='Message')),
            ],
        ),
        migrations.CreateModel(
            name='EditorObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('checkbox', 'Checkbox'), ('h1', 'Header 1'), ('h2', 'Header 2'), ('h3', 'Header 3'), ('ol', 'Ordered list'), ('ul', 'Unordered list')], max_length=10, verbose_name='Type')),
                ('content', models.TextField(blank=True, default='', verbose_name='Content')),
                ('file', models.FileField(blank=True, null=True, upload_to='jlab/editor/', verbose_name='File')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Is checked?')),
                ('order', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Order')),
                ('inline_styles', models.JSONField(blank=True, null=True, verbose_name='Inline styles')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objs', to='jlab.projecttask', verbose_name='Task')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.AddIndex(
            model_name='messageobject',
            index=models.Index(condition=models.Q(('video_id__isnull', False)), fields=['video_id'], name='message-object--video_id-index'),
        ),
    ]
