# Generated by Django 3.2.6 on 2024-10-12 10:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('text', 'Text'), ('video', 'Video'), ('image', 'Image')], default='text', max_length=25, verbose_name='Agent')),
                ('name', models.CharField(blank=True, max_length=25, verbose_name='Name')),
                ('placeholder', models.CharField(blank=True, max_length=50, verbose_name='Placeholder')),
                ('sys_template', models.TextField(blank=True, verbose_name='System prompt template')),
                ('user_template', models.TextField(blank=True, verbose_name='User prompt template')),
                ('order', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Order')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VideoAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('el_id', models.CharField(max_length=255, verbose_name='ElevenLabs ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('default_audio', models.FileField(blank=True, null=True, upload_to='jlab/avatars/audio/', verbose_name='Default audio')),
                ('default_video', models.FileField(blank=True, null=True, upload_to='jlab/avatars/video/', verbose_name='Default video')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='jlab/avatars/photo', verbose_name='Photo')),
                ('stability', models.FloatField(verbose_name='Stability')),
                ('similarity_boost', models.FloatField(verbose_name='Similarity boost')),
                ('style', models.FloatField(default=0, verbose_name='Style')),
                ('use_speaker_boost', models.BooleanField(default=True, verbose_name='Use speaker boost?')),
            ],
        ),
        migrations.CreateModel(
            name='VideoAvatarTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='jlab/avatars/templates/', verbose_name='File')),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.videoavatar', verbose_name='Avatar')),
            ],
        ),
        migrations.CreateModel(
            name='AgentImageExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to='jlab/agents/images', verbose_name='Image')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='main.agent', verbose_name='Agent')),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='avatar',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.videoavatar', verbose_name='Video avatar'),
        ),
    ]
